Added support for drpg slash commands
Nightorn/Aldebaran pull request #84
Opened 2022-04-26 17:35 UTC by RagingLink

This is very much a very quick solution and hasn't been tested for padv (even though it *should* work fine).

This also should not be deployed when drpg has not fully migrated to slash commands, as the code for the timers/health monitor have been written with slash commands in mind.

2022-04-26 19:34 UTC, Ciborn reviewed
For the sake of professionalism, I'll formalize my thoughts here.

Aside from some debatable code style changes you have made, everything looks good! Depending on how long the DiscordRPG beta will be going, it may be necessary to support both "raw input" and slash commands.
Nothing is bad about your own code style as it seems both yours and mine are being used in other projects, but I made some changes to it for the sake of consistency.

As you suggested, this pull request as is will be merged once the DiscordRPG is done. Thank you very much for your contribution!

2022-04-26 20:49 UTC, RagingLink commented
aight bet bro

2022-04-26 21:21 UTC, Ciborn requested changes
i hope this works

2022-04-26 21:21 UTC, Ciborn commented on src/events/message.ts
> +		undefined;
Considering current Aldebaran's code style, the operators should be placed after the line break.
```suggestion
	const interactionUser = message.interaction !== null
		? await client.customUsers.fetch(message.interaction.user.id)
	    : undefined;
```

2022-04-26 21:21 UTC, Ciborn commented on src/structures/contexts/DiscordMessageContext.ts
> +	constructor(client: Client,
`client`'s access specifier should be explicited, and the parameter should be placed after a line break.
```suggestion
	constructor(
		public client: Client, 
```

2022-04-26 21:21 UTC, Ciborn commented on src/structures/contexts/DiscordSlashMessageContext.ts
>  		client: Client,
`client`'s access specifier should be explicited.
```suggestion
		public client: Client,
```

2022-05-06 16:35 UTC, RagingLink commented
I will be looking into adding support for text drpg so this commit doesn't need to be timed with slash drpg.

2022-08-27 09:35 UTC, closed without merging